### ISSUE TITLE
Publish latest version

### ISSUE THREAD

**Issue by JacobLey** [foray1010/didyoumean2#1435]
Hi, I was using this package during a CJS->ESM migration and typescript stopped working.

I realized the fix for this was actually implemented a while back! Almost a year ago: https://github.com/foray1010/didyoumean2/commit/734187ddc0db49b8269ba930cf8215767f2205c4

However it is not published to npm, which is still sitting at 5.0.0 and is over 2 years old! https://github.com/foray1010/didyoumean2/commit/f011011198fd10d7ccf3883d1819e38462c9ea3c

A lot has happened since then: https://github.com/foray1010/didyoumean2/compare/v5.0.0...master and it would be great to finally release those changes to consumers

**Comment by foray1010** [comment]
Thanks for letting me know the issue! Please try if it fixes the issue you encountered: https://github.com/foray1010/didyoumean2/commit/776f9258afb90773cb8da0e3c63c22b3eb9e0f95

**Comment by JacobLey** [comment]
Wow that was fast, thank you!

I did actually have a small types issue still. Opened a PR to attempt to address: https://github.com/foray1010/didyoumean2/pull/1436
