### ISSUE TITLE
nice!!!

### ISSUE THREAD

**Issue by swift-fs** [foray1010/didyoumean2#1666]
How do I get you coffee?

**Comment by foray1010** [comment]
If you insist, you could buy me a coffee via [my another project sponsor link](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=TP67BBZ7VK934) :)

**Comment by swift-fs** [comment]
For Chinese developers, only Alipay and wechat Pay are available😭

**Comment by foray1010** [comment]
Nvm! Happy that this software is useful to you!
