### ISSUE TITLE
Browser packaging?

### ISSUE THREAD

**Issue by breck7** [foray1010/didyoumean2#179]
Neat stuff! I am a user of https://github.com/dcporter/didyoumean.js and was looking for a TypeScript version.

What I like about that version is the browser support and 1 file. Easy to copy/paste it into a larger library without requiring a dependency.

Just wanted to offer that feedback that might be useful to build for some browser targets in your "dist/" as well. Could also then build a web page with a demo.

**Comment by foray1010** [comment]
sounds like you are looking for a [UMD](https://github.com/umdjs/umd) build, I will see if I can make one this weekend

for browser support, current build output ES5 compatible syntax which supports [roughly IE9+](https://caniuse.com/#search=ECMAScript%205)

**Comment by breck7** [comment]
Thanks, I ended up doing a quick convert of didyoumean to TypeScript and using the function inline, for now.

**Comment by foray1010** [comment]
@breck7 you can have a look at v3.1.0, there is a `umd` build in `node_modules/didyoumean2/dist/index.umd.js` which should suit your needs

**Comment by breck7** [comment]
That works, thanks!
